$ANSIBLE_VAULT;1.1;AES256
36366165356264363164313431313834383664386336663738373337373534323332623736656563
6361346439333436633138636231393638346561656661320a363839333539306331666232393434
35336535653965383432373035356536643265356131353335666535303833373862633661316537
6463366633303563640a363065396430363138323439363634333464346161386536636662613664
31663934393132326165643061663463313938356335353162336232643434366366323531656361
30323133346365306336646236373163333961636437663630323934643636393137313466326133
39303032663961663562333038393438396132346434313965343235373134313534363632343862
62643434663363326530
